export const theme = {
  colors: {
    transparent: 'transparent',
    black: 'rgba(0, 0, 0, 0.8)',
    lightBlack: 'rgba(0, 0, 0, 0.6)',
    blue: '#106CD5',
    darkBlue: '#035ABE',
    grey: '#e7eaed',
    darkGrey: '#c4cbd3',
    white: '#fff',
    green: '#20bf6b',
    red: '#eb3b5a',
  },
  link: {
    color: 'black',
    textDecoration: 'none',
    '&:hover': {
      color: 'darkBlue',
    },
  },
  forms: {
    input: {
      width: '100%',
      fontSize: '14px',
      height: '48px',
      px: '16px',
      border: '1px solid',
      borderColor: 'darkGrey',
      borderRadius: '6px',
      transition: 'border-color 0.2s ease-in-out',
      ':focus': {
        outline: 'none',
        boxShadow: '0 0 0 0',
        borderColor: 'blue',
      },
      ':hover': {
        borderColor: 'blue',
      },
    },
    select: {
      cursor: 'pointer',
      borderRadius: '6px',
      background: 'transparent',
      border: '1px solid',
      borderColor: 'darkGrey',
      width: '100%',
      outline: 'none',
      py: '6px',
      pl: '12px',
      pr: '32px',
      ':hover': {
        borderColor: 'blue',
      },
    },
  },
  styles: {
    baseButton: {
      width: '100%',
      display: 'flex',
      height: '48px',
      boxSizing: 'border-box',
      cursor: 'pointer',
      alignItems: 'center',
      justifyContent: 'center',
      textDecoration: 'none',
      transition: 'all 0.2s ease-in-out',
      borderRadius: '6px',
      py: '4px',
      px: '12px',
      color: 'white',
      border: '1px solid',
      borderColor: 'blue',
      bg: 'blue',
      ':hover': {
        bg: 'darkBlue',
        color: 'white',
        borderColor: 'darkBlue',
      },
      whiteSpace: 'nowrap',
      overflow: 'hidden',
    },
  },
}
